// <auto-generated />
using API_Usage.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace API_Usage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190407022757_IntialCreated")]
    partial class IntialCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_Usage.Models.Company", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date");

                    b.Property<string>("iexId");

                    b.Property<bool>("isEnabled");

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("symbol");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("API_Usage.Models.Dividend_Model", b =>
                {
                    b.Property<string>("exdate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("declaredDate");

                    b.Property<string>("paymentDate");

                    b.Property<string>("qualified");

                    b.Property<string>("recordDate");

                    b.Property<string>("type");

                    b.HasKey("exdate");

                    b.ToTable("Dividend");
                });

            modelBuilder.Entity("API_Usage.Models.Equity", b =>
                {
                    b.Property<int>("EquityId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("change");

                    b.Property<float>("changeOverTime");

                    b.Property<float>("changePercent");

                    b.Property<float>("close");

                    b.Property<string>("date");

                    b.Property<float>("high");

                    b.Property<string>("label");

                    b.Property<float>("low");

                    b.Property<float>("open");

                    b.Property<string>("symbol");

                    b.Property<int>("unadjustedVolume");

                    b.Property<int>("volume");

                    b.Property<float>("vwap");

                    b.HasKey("EquityId");

                    b.HasIndex("symbol");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("API_Usage.Models.Infocus_Model", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("avgTotalVolume");

                    b.Property<string>("calculationPrice");

                    b.Property<double>("change");

                    b.Property<double>("changePercent");

                    b.Property<float>("close");

                    b.Property<long>("closeTime");

                    b.Property<string>("companyName");

                    b.Property<double>("delayedPrice");

                    b.Property<long>("delayedPriceTime");

                    b.Property<double>("extendedChange");

                    b.Property<double>("extendedChangePercent");

                    b.Property<long>("extendedPrice");

                    b.Property<long>("extendedPriceTime");

                    b.Property<float>("high");

                    b.Property<string>("iexAskPrice");

                    b.Property<string>("iexAskSize");

                    b.Property<string>("iexBidPrice");

                    b.Property<string>("iexBidSize");

                    b.Property<string>("iexLastUpdated");

                    b.Property<string>("iexMarketPercent");

                    b.Property<string>("iexRealtimePrice");

                    b.Property<string>("iexRealtimeSize");

                    b.Property<string>("iexVolume");

                    b.Property<double>("latestPrice");

                    b.Property<string>("latestSource");

                    b.Property<string>("latestTime");

                    b.Property<long>("latestUpdate");

                    b.Property<int>("latestVolume");

                    b.Property<double>("low");

                    b.Property<long>("marketCap");

                    b.Property<string>("open");

                    b.Property<long>("openTime");

                    b.Property<string>("peRatio");

                    b.Property<double>("previousClose");

                    b.Property<string>("primaryExchange");

                    b.Property<string>("sector");

                    b.Property<float>("week52High");

                    b.Property<float>("week52Low");

                    b.Property<double>("ytdChange");

                    b.HasKey("symbol");

                    b.ToTable("InFocus");
                });

            modelBuilder.Entity("API_Usage.Models.News_Model", b =>
                {
                    b.Property<DateTime>("datetime");

                    b.Property<string>("headline");

                    b.Property<string>("image");

                    b.Property<string>("related");

                    b.Property<string>("source");

                    b.Property<string>("summary");

                    b.Property<string>("url");

                    b.HasKey("datetime");

                    b.ToTable("News");
                });

            modelBuilder.Entity("API_Usage.Models.SectorPerformance_Model", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("lastUpdated");

                    b.Property<float>("performance");

                    b.Property<string>("type");

                    b.HasKey("name");

                    b.ToTable("SectorPerform");
                });

            modelBuilder.Entity("API_Usage.Models.Equity", b =>
                {
                    b.HasOne("API_Usage.Models.Company")
                        .WithMany("Equities")
                        .HasForeignKey("symbol");
                });
#pragma warning restore 612, 618
        }
    }
}
